### ISSUE TITLE
cores flag unused in enrichment_stats.sh

### ISSUE THREAD

**Issue by davidecarlson** [dovetail-genomics/HiChiP#5]
Dear Dovetail developers,

Thank you for making this resource available.  I've found it useful for analyzing HiChIP data.

It seems that the `enrichment_stats.sh` script takes an argument called `cores`, which would seem to imply that some level of user-configurable parallelization exists, but the flag is not actually used in the script.  I believe the entire process is serial.  The enrichment analysis is relatively quick, so this is not a problem, but I just wanted to point out the unused flag.

Best,
Dave

**Comment by mlkhawand** [comment]
Dave, thank you for your note. The HiChIP workflow is also available on readthedocs: https://hichip.readthedocs.io/en/latest/. This is the page where we are making updates when they arise.

Best,
Myriam

**Comment by davidecarlson** [comment]
Thanks, Myriam.  I have been following the workflow on the readthedocs site.  It's very helpful!

Best,
Dave
